### ISSUE TITLE
Cannot install!

### ISSUE THREAD

**Issue by soewaiyanmyowin** [naman14/adb-tools-mac#7]
I cannot install this on my macbook pro (2018) with macOS bigSur 11.2.3. Hope it gets fix  soon. I would be very pleased to use this. thz for ur effort and contribution to  opensource community.
below is the screenshot .... 

![image](https://user-images.githubusercontent.com/38293630/111116870-070f5a00-8595-11eb-8c52-8d5c0b7fd149.png)

**Comment by pieterclaerhout** [comment]
Right-click on it and select "Open".

The app probably isn't notarized and/or codesigned properly…

**Comment by SoeWaiYan** [comment]
> Right-click on it and select "Open".
> 
> The app probably isn't notarized and/or codesigned properly…

tried , doesn't work .
